# Generated by Django 3.2.7 on 2021-11-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='title',
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.CharField(default='nada', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='song',
            field=models.CharField(default='nada', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='thumbnail',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
